// S9 t3 — Daemon MCP client.
//
// Store-touching commands (`status`, `context *`, `memory *`, `task *`) are thin
// MCP clients over the running Noir daemon rather than opening the store
// in-process: that preserves the daemon's single-writer discipline and reuses
// the MCP tool surface built in S6. This module is the single bridge from
// the CLI to that daemon — every command module calls {@link callDaemonTool} (or
// the multi-call {@link withDaemon}) instead of importing the store directly.
//
// Flow: {@link ensureDaemonRunning} (from @noir-ai/daemon) reads THIS project's
// daemon record (`~/.noir/daemons/<projectId>.json`, NOIR_DAEMON_DIR override
// for tests) and STARTS a foreground daemon if no healthy one is present,
// returning its URL + a `stop()` tear-down. We connect a
// @modelcontextprotocol/client `Client` over
// Streamable HTTP to that URL (127.0.0.1 only — daemon §4), initialize, and
// `callTool(name, args)`; the daemon's tools always return a single text content
// block whose `text` is `JSON.stringify(payload)` (see `textResult` in
// packages/daemon/src/server.ts), so we parse it back into the payload object.
//
// Failure handling (S9 exit-code contract): ANY failure to reach or use the
// daemon — record missing/stale, ensure-start error, transport, connect,
// protocol, or a tool call that rejects / returns no parseable text — maps to
// exit code `4` (DAEMON_DOWN) with a stable remediation hint. `--verbose` surfaces
// the underlying cause on stderr; `--json` shapes the failure as the S9
// `{ok:false,error:{code,message}}` envelope ON STDOUT via `output.ts:fail`
// (data→stdout discipline — the single canonical envelope is shaped once there;
// `failDaemonDown` passes the PLAIN hint as the message, never a pre-stringified
// inner envelope, which would doubly-encode `error.message`). A tool that returns
// a logical-failure envelope (`{ok:false, degraded:true, …}`) is NOT a transport
// failure — it parses cleanly and is returned to the caller as data.
//
// Auth (spec 6.1): the HTTP transport requires a bearer token, regenerated by
// the daemon on every start and stored 0600 at `~/.noir/daemons/<scopeKey>.token`
// (`readDaemonToken`). The scope key is the daemon's IDENTITY: a project daemon's
// projectId, a workspace daemon's workspace NAME (spec §6.3). Every `/mcp`
// connect below sends the token for the daemon it is addressing via
// `httpTransport` — never another identity's; `/health` is token-free, so the
// liveness probe and the daemon record are unaffected. The stdio transport never
// uses a token (no network surface, no header trust).

import { Client, StreamableHTTPClientTransport } from '@modelcontextprotocol/client';
import { ContextEngine, createEmbedFn, resolveEmbedderConfig } from '@noir-ai/context';
import {
  loadProjectInfo,
  NOIR_VERSION,
  type ProjectInfo,
  readWorkspaceMarker,
  workspaceStoreDbPath,
} from '@noir-ai/core';
import {
  ensureDaemonRunning,
  pidAlive,
  readDaemonToken,
  readProjectDaemonRecord,
  readWorkspaceDaemonRecord,
  resolveGateConfig,
  tokenPath,
} from '@noir-ai/daemon';
import { createMemoryEngine, type MemoryEngine } from '@noir-ai/memory';
import { openStore, type Store } from '@noir-ai/store';
import { WorkflowEngine } from '@noir-ai/workflow';
import { EXIT, fail } from './bin.js';

/** Options shared by every daemon-client entry point. */
export interface DaemonClientOptions {
  /** Emit the daemon-down failure as a JSON `{ok,error}` envelope (S9 --json). */
  readonly json?: boolean;
  /** Surface transport / connection detail on stderr (S9 --verbose). */
  readonly verbose?: boolean;
  /**
   * Project used to resolve the daemon idle timeout. Defaults to
   * `loadProjectInfo(process.cwd())` — the bin's `--cwd` preAction hook has
   * already chdir'd, so process.cwd() honors `--cwd`.
   */
  readonly project?: ProjectInfo;
  /** Override the daemon idle timeout (sec). Defaults to the project's config. */
  readonly idleTimeoutSec?: number;
}

/** A handle for calling daemon MCP tools over an already-connected client. */
export interface DaemonToolCaller {
  /**
   * Call a daemon MCP tool and parse its text-JSON result. Transport / parse
   * failures throw an S9 {@link NoirCliError} (exit 4); a tool's own logical
   * failure envelope (`{ok:false,…}`) is returned as-is.
   */
  callTool<T = unknown>(name: string, args?: Record<string, unknown>): Promise<T>;
  /**
   * List the names of the tools the connected daemon currently exposes.
   * Required so a command can tell "the daemon is up but does not register
   * tool X" (an opt-in / engine-not-wired condition, e.g. `memory_consolidate`
   * when consolidation is disabled) apart from "the daemon is down" — calling
   * an unregistered tool would otherwise mis-map onto exit 4 (DAEMON_DOWN).
   * Transport failures throw exit 4 exactly like {@link callTool}.
   */
  listTools(): Promise<string[]>;
}

/** Daemon-down remediation hint (S9). Stable across releases. */
export const DAEMON_DOWN_HINT = 'daemon not reachable — try `noir daemon start`';

/**
 * Bounded /health probe window (ms). A probe must never hang: a stale daemon
 * record can point at a port bound by an unrelated process that accepts TCP but
 * never answers, and the probe is now the FIRST hop for every read command's
 * fallback decision. A timeout is treated as "not running" (reads degrade to the
 * read-only engine); the bound also keeps the daemon-up fast path snappy.
 */
export const PROBE_TIMEOUT_MS = 1500;

function describeCause(cause: unknown): string {
  if (cause instanceof Error) return `${cause.name}: ${cause.message}`;
  try {
    return JSON.stringify(cause);
  } catch {
    return String(cause);
  }
}

/**
 * Map any daemon / transport failure onto the S9 DAEMON_DOWN exit code. Always
 * throws (via {@link fail}); the `never` return lets callers use it as a
 * diverging expression inside parsed result handling.
 */
function failDaemonDown(opts: DaemonClientOptions, cause: unknown): never {
  if (opts.verbose) {
    process.stderr.write(`noir: daemon transport detail: ${describeCause(cause)}\n`);
  }
  // Pass the PLAIN hint + opts and let `output.ts:fail` shape the single S9
  // `{ok:false,error:{code:EXIT.DAEMON_DOWN,message:hint}}` envelope ONCE. The
  // prior branch pre-stringified an inner `{ok,error}` and passed it as `message`,
  // which `fail` then wrapped AGAIN → `error.message` was a JSON string
  // (doubly-encoded). `opts` carries `--json`/`--verbose` so `fail` selects the
  // stdout envelope vs. the plain stderr line.
  fail(EXIT.DAEMON_DOWN, DAEMON_DOWN_HINT, opts);
}

// ---------------------------------------------------------------------------
// Liveness probe (read-only). `noir status` uses this to report daemon state
// HONESTLY without auto-starting one: it reads the daemon record + checks the
// pid + GETs /health, and returns {running:false} on any miss. It NEVER calls
// ensureDaemonRunning. Active commands keep using {@link withDaemon} (which may
// start a daemon); only the informational `status` command is probe-only.
// ---------------------------------------------------------------------------

/** Outcome of a read-only daemon liveness probe (never starts a daemon). */
export interface DaemonProbe {
  running: boolean;
  pid?: number;
  port?: number;
  uptimeSec?: number;
}

/**
 * Probe whether a healthy daemon is currently running, WITHOUT starting one.
 * Resolves the CALLER's project id first (that id IS the record lookup key),
 * reads the per-project record via {@link readProjectDaemonRecord}, checks
 * {@link pidAlive}, and GETs `http://127.0.0.1:<port>/health`. Any miss (no
 * project, no record, stale pid, non-200, unreachable, malformed body) →
 * `{running:false}` — this function NEVER throws and NEVER starts a daemon.
 * Under `--verbose` the reason for a miss is logged to stderr (NF5: honest
 * degradation).
 */
export async function probeDaemon(opts: DaemonClientOptions = {}): Promise<DaemonProbe> {
  // Resolve the project FIRST — with per-project records the ProjectId IS the
  // lookup key, so the record cannot be read before it is known.
  const expectedProject =
    opts.project?.id ??
    (() => {
      try {
        return loadProjectInfo(process.cwd()).id;
      } catch {
        return undefined; // uninitialized — no caller project to look up
      }
    })();
  if (expectedProject === undefined) {
    if (opts.verbose) process.stderr.write('noir: daemon probe: no project (uninitialized)\n');
    return { running: false };
  }
  const rec = readProjectDaemonRecord(expectedProject);
  if (!rec) {
    if (opts.verbose) process.stderr.write('noir: daemon probe: no daemon record\n');
    return { running: false };
  }
  if (!pidAlive(rec.pid)) {
    if (opts.verbose) process.stderr.write(`noir: daemon probe: pid ${rec.pid} not alive\n`);
    return { running: false };
  }
  try {
    // Bounded probe: a stale daemon record pointing at a port held by an
    // unrelated process that accepts TCP but never responds (a blackhole) must
    // NOT hang the probe (or any read command that probes first). Treat a
    // timeout as "not running" so reads fall back to the read-only engine.
    const res = await fetch(`http://127.0.0.1:${rec.port}/health`, {
      signal: AbortSignal.timeout(PROBE_TIMEOUT_MS),
    });
    if (!res.ok) {
      if (opts.verbose) process.stderr.write(`noir: daemon probe: /health → HTTP ${res.status}\n`);
      return { running: false };
    }
    const body = (await res.json().catch(() => null)) as {
      ok?: boolean;
      pid?: number;
      uptimeSec?: number;
    } | null;
    // PID-reuse guard (same invariant as @noir-ai/daemon ensure.ts isHealthy +
    // commands/daemon.ts isHealthy): the responding /health must carry OUR
    // recorded pid — a missing or mismatched pid means a foreign process holds
    // the port; report NOT running. (The record is already scoped to the caller's
    // project, so there is no cross-project body check left to perform.)
    const pidOk = typeof body?.pid === 'number' && body.pid === rec.pid;
    if (body?.ok !== true || !pidOk) {
      if (opts.verbose)
        process.stderr.write(
          !pidOk
            ? 'noir: daemon probe: pid missing/mismatched (foreign process on recorded port)\n'
            : 'noir: daemon probe: /health body not ok\n',
        );
      return { running: false };
    }
    return {
      running: true,
      pid: typeof body.pid === 'number' ? body.pid : rec.pid,
      port: rec.port,
      uptimeSec: typeof body.uptimeSec === 'number' ? body.uptimeSec : undefined,
    };
  } catch (err) {
    if (opts.verbose)
      process.stderr.write(`noir: daemon probe: unreachable (${describeCause(err)})\n`);
    return { running: false };
  }
}

/**
 * Resolve a CONNECTED daemon client for the caller's project, plus the
 * tear-down for any daemon this call started. Maps any start / connect error
 * onto exit 4.
 *
 * Ordering is CONNECT-FIRST (spec 7.1). When `daemon.port` gives a stable
 * address we attempt the MCP session against it BEFORE spawning anything, so a
 * daemon starts because a connection was genuinely attempted rather than as a
 * side effect of running a command. Only when that attempt fails — a refused
 * connection is the common case — do we fall through to
 * {@link ensureDaemonRunning} (still the single spawn primitive; only the
 * DECISION POINT moved) and connect to whatever it returns. Without a
 * configured `daemon.port` there is no address to probe, so the previous
 * ensure-first ordering is retained verbatim (spec 7.1: D depends on B).
 *
 * The failure path is BOUNDED, in both senses. Structurally: at most one direct
 * attempt, one ensure, and one retry connect — never a loop. In time: the direct
 * probe is raced against {@link PROBE_TIMEOUT_MS}, so a port that accepts TCP
 * and never answers ("blackhole") costs the probe window, not a multi-minute
 * stall. A permanently dead port therefore ends in the S9 exit-4 DAEMON_DOWN
 * envelope via {@link failDaemonDown}, not a hang.
 *
 * This function cleans up after ITSELF before any throw: every client it created
 * is closed, and a daemon it started (an ensure result's `stop`) is torn down —
 * because throwing from here means `withDaemon`'s `finally` never runs, so the
 * caller's tear-down cannot be relied on for this leg.
 */
async function resolveDaemon(
  opts: DaemonClientOptions,
): Promise<{ client: Client; stop: () => Promise<void> }> {
  // Lazy default: when the caller didn't inject a project (the common case from
  // command modules, which only forward --json/--verbose), resolve one here.
  // An uninitialized project (`loadProjectInfo` throws "Run `noir init` first")
  // is a USAGE error (exit 1), not a daemon-down (exit 4) — so route it through
  // fail() BEFORE the ensureDaemonRunning try, which maps errors to exit 4. This
  // keeps exit-1 semantics AND emits the canonical {ok:false,error} envelope on
  // stdout under --json (a plain Error would leave stdout EMPTY). It also runs
  // BEFORE any connect attempt: a project id is the daemon scope key, so there
  // is nothing to address (and no token to present) without one.
  let project: ProjectInfo;
  try {
    project = opts.project ?? loadProjectInfo(process.cwd());
  } catch {
    fail(EXIT.ERROR, 'Noir is not initialized in this directory. Run `noir init` first.', opts);
  }
  const idleTimeoutSec = opts.idleTimeoutSec ?? project.config.daemon.idleTimeoutSec;
  const preferred = project.config.daemon.port;

  // Connect-first when a stable address exists. `0` is a configured PREFERENCE
  // for an ephemeral port, i.e. explicitly NOT a stable address — it takes the
  // ensure-first path below, which still forwards the preference to the spawn.
  if (preferred !== undefined && preferred !== 0) {
    const direct = `http://127.0.0.1:${preferred}/mcp`;
    const probe = newClient();
    let probeTimer: ReturnType<typeof setTimeout> | undefined;
    try {
      // Raw connect, NOT connectClient: a failure here is the SIGNAL TO SPAWN,
      // not a command-fatal error, so it must never be mapped onto exit 4.
      //
      // BOUNDED, exactly like every other address probe in this module: a
      // configured port is a BLIND address — unlike the port
      // `ensureDaemonRunning` has just verified via `/health`, a foreign process
      // may hold it and accept TCP without ever answering. `connect()` carries
      // no deadline of its own (the only backstop would be undici's ~300s
      // headersTimeout), so the probe is raced against the same
      // {@link PROBE_TIMEOUT_MS} window the `/health` probe uses and a timeout
      // is treated as "no daemon here", i.e. fall through to the spawn.
      await Promise.race([
        probe.connect(httpTransport(direct, project.id)),
        new Promise<never>((_, reject) => {
          probeTimer = setTimeout(
            () => reject(new Error(`no response within ${PROBE_TIMEOUT_MS}ms`)),
            PROBE_TIMEOUT_MS,
          );
        }),
      ]);
      // A daemon was already answering at the configured address. Nothing was
      // started, so tear-down is a no-op — `stop` must stay inert (there is no
      // ensure result to defer to, and stopping a daemon we did not start would
      // kill the user's).
      return { client: probe, stop: async () => {} };
    } catch (err) {
      // Refused connection (nothing listening), no answer inside the probe
      // window (a blackhole port), a stale token from a before-restart daemon,
      // or a foreign process holding the port — each means "no USABLE daemon at
      // this address". Discard the probe and fall through to ensure + one retry;
      // the token is re-read at retry connect time, so a stale-token case
      // self-heals against the same (still healthy) daemon.
      if (opts.verbose) {
        process.stderr.write(
          `noir: no daemon at the configured port ${preferred} (${describeCause(err)})\n`,
        );
      }
      await probe.close().catch(() => {
        /* the probe connection is already unusable; never mask the spawn path */
      });
    } finally {
      // Release the loser: on success the pending timer must not hold the event
      // loop open, and on failure it has already fired. (A connect that settles
      // AFTER the timeout is ignored by the settled race — and `close()` above
      // has already torn its transport down.)
      if (probeTimer !== undefined) clearTimeout(probeTimer);
    }
  }

  let url: string;
  let stop: () => Promise<void>;
  try {
    const ensured = await ensureDaemonRunning({
      project,
      idleTimeoutSec,
      ...(preferred !== undefined ? { port: preferred } : {}),
    });
    url = ensured.url;
    stop = ensured.stop;
  } catch (err) {
    failDaemonDown(opts, err);
  }

  // The retry (or the direct path when no port is configured). A failure HERE
  // is genuinely fatal — ensure already succeeded, so there is no further
  // recovery and the S9 exit-4 mapping applies (unlike the probe above).
  const client = newClient();
  try {
    await connectClient(client, url, opts, project.id);
  } catch (err) {
    // This function is about to THROW, so `withDaemon`'s finally — the one that
    // tears down a daemon we started — never runs. Tear down BOTH here, or a
    // daemon `ensureDaemonRunning` just spawned is stranded (running, with no
    // caller left to stop it) behind an exit-4 failure. Reachable on the plain
    // ensure-first path too, not just connect-first: ensure succeeds, then the
    // connect to the daemon it returned fails.
    await client.close().catch(() => {
      /* never mask the connect failure with a close failure */
    });
    await stop().catch(() => {
      /* ditto for the tear-down — the connect failure is the real error */
    });
    throw err;
  }
  return { client, stop };
}

/**
 * Build a Streamable HTTP transport for `url`, carrying the daemon's bearer
 * token when one is on disk for `scopeKey`. The daemon regenerates its token
 * on every start (spec 6.1), so the header is resolved at CONNECT time — never
 * cached across commands — and an absent token file simply means "send no
 * header" (a stdio-only or pre-auth daemon); the request then fails as any
 * other unauthorized request does (exit 4 with the daemon's own remediation).
 * `scopeKey` is the daemon identity: a project daemon's projectId, a workspace
 * daemon's name.
 */
function httpTransport(url: string, scopeKey: string | null): StreamableHTTPClientTransport {
  const token = scopeKey === null ? null : readDaemonToken(scopeKey);
  return new StreamableHTTPClientTransport(
    new URL(url),
    // Verified present: StreamableHTTPClientTransportOptions.requestInit?: RequestInit
    token ? { requestInit: { headers: { Authorization: `Bearer ${token}` } } } : {},
  );
}

/**
 * The daemon scope key for the caller's project (its projectId), or `null` when
 * the project cannot be resolved. `null` ⇒ connect without a token header; the
 * daemon then answers 401 and the caller maps it to exit 4 exactly like any
 * other unreachable daemon (the caller has no project to scope a token to).
 */
function callerScopeKey(opts: DaemonClientOptions): string | null {
  try {
    return (opts.project ?? loadProjectInfo(process.cwd())).id;
  } catch {
    return null;
  }
}

/**
 * Build an unconnected MCP client for the CLI. One client per connection: the
 * SDK's `connect` binds a transport to the client, so a client is never reused
 * across two daemons (the connect-first probe discards its own on failure).
 */
function newClient(): Client {
  return new Client(
    { name: 'noir-cli', version: NOIR_VERSION },
    { versionNegotiation: { mode: 'auto' } },
  );
}

/** Connect a Client over Streamable HTTP, rethrowing the RAW transport error so
 *  the caller owns the failure mapping. Used by {@link withWorkspaceDaemon},
 *  which can read more out of a connect failure than "the daemon is down" (a
 *  401 means it is up and reachable but rejected our credential). Everything
 *  else goes through {@link connectClient}, which maps onto exit 4. */
async function connectRaw(client: Client, url: string, scopeKey: string | null): Promise<void> {
  await client.connect(httpTransport(url, scopeKey));
}

/** Connect a Client over Streamable HTTP; map transport failure to exit 4. */
async function connectClient(
  client: Client,
  url: string,
  opts: DaemonClientOptions,
  scopeKey: string | null,
): Promise<void> {
  try {
    await connectRaw(client, url, scopeKey);
  } catch (err) {
    failDaemonDown(opts, err);
  }
}

/**
 * Map a WORKSPACE connect failure onto exit 4 with an accurate message.
 *
 * A 401 is not "the daemon is down": the daemon answered, so it IS reachable —
 * it rejected our bearer token (a stale token file, or one we cannot read). The
 * generic {@link DAEMON_DOWN_HINT} sends the user to `noir daemon start`, which
 * fixes nothing. Name the token file (the workspace scope key is the workspace
 * NAME) and the remedy instead. Conservative by construction: only the MESSAGE
 * differs for the recognizable-401 case — the exit code and every non-401
 * failure keep the exact previous behaviour.
 */
function failWorkspaceConnect(
  opts: DaemonClientOptions,
  routing: WorkspaceRouting,
  cause: unknown,
): never {
  const text = String(cause).toLowerCase();
  if (text.includes('401') || text.includes('unauthorized')) {
    if (opts.verbose) {
      process.stderr.write(`noir: daemon transport detail: ${describeCause(cause)}\n`);
    }
    // Names only, never a value: the token file's path, never its contents.
    fail(
      EXIT.DAEMON_DOWN,
      `workspace ${JSON.stringify(routing.name)} daemon is running but rejected this client's token (HTTP 401) — its token file is ${tokenPath(routing.name)}; make sure it is readable, or restart the workspace daemon with \`noir daemon start --workspace ${routing.name}\` to mint a fresh one.`,
      opts,
    );
  }
  failDaemonDown(opts, cause);
}

/**
 * Call one daemon tool and parse its text-JSON result. A tool's own
 * logical-failure envelope is returned as data; transport / parse failures
 * throw exit 4.
 */
async function callToolParse<T>(
  client: Client,
  opts: DaemonClientOptions,
  name: string,
  args: Record<string, unknown>,
): Promise<T> {
  // `.catch` whose handler returns `never` (failDaemonDown always throws) keeps
  // `result` typed as the callTool payload — no evolving-any `let`, and the only
  // way past this line is a successful call.
  const result = await client
    .callTool({ name, arguments: args })
    .catch((err: unknown) => failDaemonDown(opts, err));
  // The daemon's tools always return `{content:[{type:'text', text: JSON}]}` via
  // `textResult`. Read defensively: any non-text / empty / non-JSON block means
  // the MCP surface is unusable → exit 4 (not a tool's logical error).
  const block = (result.content as readonly unknown[] | undefined)?.[0] as
    | { type?: string; text?: unknown }
    | undefined;
  if (block?.type !== 'text' || typeof block.text !== 'string') {
    failDaemonDown(opts, new Error(`tool '${name}' returned no text content`));
  }
  const text: string = block.text;
  try {
    return JSON.parse(text) as T;
  } catch (err) {
    failDaemonDown(opts, err);
  }
}

/**
 * Build a {@link DaemonToolCaller} over an already-connected {@link Client}.
 * Shared by {@link withDaemon} (active commands — failures map to exit 4) and
 * {@link withRunningDaemon} (status — connect failures degrade to null, caught
 * by its outer try). `callTool`/`listTools` still route transport / parse
 * failures through {@link failDaemonDown}; {@link withRunningDaemon} wraps the
 * connect+fn body so those become a null result instead of an exit.
 */
function buildCaller(client: Client, opts: DaemonClientOptions): DaemonToolCaller {
  return {
    callTool: <U = unknown>(name: string, args: Record<string, unknown> = {}): Promise<U> =>
      callToolParse<U>(client, opts, name, args),
    listTools: async (): Promise<string[]> => {
      // `listTools()` is the standard MCP capability discovery method; the
      // daemon's McpServer answers with every registered tool name. Any
      // transport failure maps to exit 4 (DAEMON_DOWN) exactly like callTool;
      // a defensive read of `.tools` keeps a surprising payload from crashing.
      const res = await client.listTools().catch((err: unknown) => failDaemonDown(opts, err));
      const tools = (res as { tools?: unknown } | null)?.tools;
      if (!Array.isArray(tools)) return [];
      const names: string[] = [];
      for (const t of tools) {
        const name = (t as { name?: unknown } | null)?.name;
        if (typeof name === 'string') names.push(name);
      }
      return names;
    },
  };
}

/**
 * Connect to the daemon and run `fn` against a {@link DaemonToolCaller} that
 * shares one MCP connection across any number of tool calls.
 *
 * {@link resolveDaemon} owns the CONNECT-FIRST ordering (spec 7.1) and returns
 * a connection it has already established, so this body only has to run `fn`
 * and tear down. The client is closed and any daemon this call started is torn
 * down in `finally`, even when `fn` throws — so a one-shot CLI command never
 * strands a server or leaks a connection, while a reused (already-running)
 * daemon is left untouched (both `ensureDaemonRunning`'s `stop` for a reused
 * daemon and the connect-first path's `stop` are no-ops in that case).
 *
 * That `finally` is reached only once `resolveDaemon` has RETURNED. A throw from
 * `resolveDaemon` itself (exit 4) skips it entirely, so the same tear-down is
 * performed inside `resolveDaemon` before it throws — the two legs must stay in
 * step, or a spawned daemon is stranded. See the retry-failure catch there.
 *
 * `fn`'s own errors propagate untouched (the command module owns their exit
 * code); only transport / connection / tool-parse failures map to exit 4 here.
 */
export async function withDaemon<T>(
  opts: DaemonClientOptions,
  fn: (caller: DaemonToolCaller) => Promise<T>,
): Promise<T> {
  const { client, stop } = await resolveDaemon(opts);
  try {
    return await fn(buildCaller(client, opts));
  } finally {
    await client.close().catch(() => {
      /* a close error must not mask the real failure / swallowed result */
    });
    await stop().catch(() => {
      /* ditto: tear-down failures never override the command's outcome */
    });
  }
}

/**
 * Connect to an ALREADY-RUNNING daemon (located via {@link probeDaemon}) and run
 * `fn` over one MCP connection. NEVER starts a daemon — returns `null` when the
 * probe finds none. This is the read-only, best-effort path `noir status` uses:
 * a down daemon is reported honestly (the caller renders `daemon:{running:false}`
 * and exits 0 — status is informational, not a write), and any connect failure
 * that crops up after a successful probe (the daemon died mid-snapshot) degrades
 * to `null` rather than escalating to exit 4 (DAEMON_DOWN). Active commands that
 * NEED a daemon use {@link withDaemon} (which auto-starts + maps failures to
 * exit 4); only `status` is probe-only.
 *
 * `fn` should wrap its own tool calls in a try/catch (status uses `tryTool`) so a
 * single missing engine folds to `null` instead of failing the snapshot.
 *
 * `probe` lets a caller that has ALREADY probed (status, to populate the daemon
 * section whether up or down) pass the result in so we don't GET /health twice.
 */
export async function withRunningDaemon<T>(
  opts: DaemonClientOptions,
  fn: (caller: DaemonToolCaller) => Promise<T>,
  probe?: DaemonProbe,
): Promise<T | null> {
  const p = probe ?? (await probeDaemon(opts));
  if (!p.running) return null;
  const url = `http://127.0.0.1:${p.port}/mcp`;
  let client: Client | undefined;
  try {
    client = newClient();
    const connected: Client = client;
    // Connect directly to the probed port — NO ensureDaemonRunning. If the daemon
    // died between probe and connect (a race), this throws and we degrade to null
    // (the probe already supplied pid/uptime for the snapshot). The bearer header
    // is required here too: /health is token-free (the probe above passed without
    // one), but the /mcp snapshot connect is authenticated like every other one.
    await connected.connect(httpTransport(url, callerScopeKey(opts)));
    return await fn(buildCaller(connected, opts));
  } catch {
    // Best-effort: probe said up but connect/transport failed mid-snapshot.
    // Report the probe data + null sections instead of exit 4.
    return null;
  } finally {
    if (client) {
      await client.close().catch(() => {
        /* a close error must not mask the degraded result */
      });
    }
  }
}

/**
 * Call a single daemon MCP tool and return its parsed JSON payload. The
 * convenience most command modules use; built on {@link withDaemon} so connect
 * + close + tear-down are handled once.
 */
export async function callDaemonTool<T = unknown>(
  opts: DaemonClientOptions,
  name: string,
  args: Record<string, unknown> = {},
): Promise<T> {
  return withDaemon<T>(opts, (caller) => caller.callTool<T>(name, args));
}

// ---------------------------------------------------------------------------
// In-process read-only fallback (S9 DS-5). READS only — the single-writer
// invariant is preserved because the store is opened READ-ONLY and every engine
// built over it (context retriever, memory recall/sessions, workflow status) is
// a pure reader. Writes keep the daemon-required path (exit 4 when down).
// ---------------------------------------------------------------------------

/** Engines constructed in-process by {@link withInProcessRead} (reads only). */
export interface InProcessEngines {
  /** Hybrid-retrieval engine over the read-only store handle. */
  context: ContextEngine;
  /** Cross-session memory engine over the same handle (recall/sessions read). */
  memory: MemoryEngine;
  /** Workflow engine over the same handle (status read). */
  workflow: WorkflowEngine;
}

/**
 * Open the project's store READ-ONLY, build the context + memory + workflow
 * engines in-process over that one handle, run `fn`, and close the store in
 * `finally`. This is the daemon-down fallback for READ commands (`context
 * search`, `memory recall`, `memory sessions`, `task status`): a read-only
 * handle preserves the daemon's single-writer discipline (the store is never
 * opened for writes here), and reads (FTS, kNN, counts, KV) keep working on it
 * exactly as they do for a degraded daemon handle.
 *
 * Construction mirrors {@link openStoreForDaemon} + the daemon's stdio/http
 * seams: the context engine resolves its embedder from the project's
 * `context:` config via {@link resolveEmbedderConfig} (a pure projection —
 * construction never touches the network or the native runtime; a `kind:'none'`
 * or unavailable embedder degrades reads to BM25-only, F8); the memory engine
 * shares the SAME embed; the workflow engine reads the store KV. All three
 * reuse the injected handle — no second connection.
 *
 * `storeDegraded: true` is threaded into both engines so their persistent
 * `degraded` flag is honest (a read-only handle) and any accidental write
 * refuses with the daemon's "store is read-only (daemon down)" error rather
 * than silently succeeding.
 *
 * The store is ALWAYS closed in `finally`, even when `fn` throws (a one-shot
 * CLI command never strands a handle).
 *
 * @param opts Daemon-client options. `project` resolves the store path + the
 *   embedder config; when absent it is resolved from `process.cwd()`
 *   (uninitialized project → throws the "Run `noir init` first" exit-1 hint,
 *   mirroring {@link resolveDaemon}).
 */
export async function withInProcessRead<T>(
  opts: DaemonClientOptions,
  fn: (engines: InProcessEngines) => Promise<T>,
): Promise<T> {
  let project: ProjectInfo;
  try {
    project = opts.project ?? loadProjectInfo(process.cwd());
  } catch {
    fail(EXIT.ERROR, 'Noir is not initialized in this directory. Run `noir init` first.', opts);
  }
  // Route a store-open failure through fail() so --json emits {ok:false,error}
  // (a raw throw would leave stdout empty).
  let store: Store;
  try {
    store = await openStore({ projectId: project.id, root: project.root, readonly: true });
  } catch (err) {
    fail(
      EXIT.ERROR,
      `could not open the store read-only: ${err instanceof Error ? err.message : String(err)}`,
      opts,
    );
  }
  try {
    // READ-ONLY handle: `storeDegraded` is threaded so status/degraded flags are
    // honest and any accidental write refuses cleanly (single writer preserved).
    const embedderCfg = resolveEmbedderConfig(project.config.context);
    const embed = createEmbedFn(embedderCfg).embed;
    const context = new ContextEngine({
      store,
      root: project.root,
      projectId: project.id,
      embedderCfg,
      storeDegraded: true,
    });
    const memory = createMemoryEngine({
      store,
      root: project.root,
      projectId: project.id,
      embed,
      storeDegraded: true,
    });
    const workflow = new WorkflowEngine(
      store,
      project.root,
      project.id,
      resolveGateConfig(project.config),
    );
    return await fn({ context, memory, workflow });
  } finally {
    await store.close().catch(() => {
      /* a close error must not mask the command's outcome */
    });
  }
}

// ---------------------------------------------------------------------------
// Workspace-aware routing (ADR-0009). In a repo that joined a workspace (a
// `.noir/workspace.json` marker), `memory *` commands route to the WORKSPACE
// daemon (`?p=<projectId>`), not the per-project daemon. The read fallback opens
// the workspace store read-only (single-writer preserved). Context/workflow/task
// commands keep the project daemon (spec §6).
// ---------------------------------------------------------------------------

/** A repo's workspace membership (name + this repo's project id), or null. */
export interface WorkspaceRouting {
  name: string;
  projectId: string;
}

export function workspaceRoutingTarget(root: string): WorkspaceRouting | null {
  const name = readWorkspaceMarker(root);
  if (name === null) return null;
  try {
    return { name, projectId: loadProjectInfo(root).id };
  } catch {
    return null;
  }
}

/** Read-only probe of a workspace daemon (never starts one). */
export async function probeWorkspaceDaemon(routing: WorkspaceRouting): Promise<DaemonProbe> {
  const rec = readWorkspaceDaemonRecord(routing.name);
  if (rec === null || !pidAlive(rec.pid)) return { running: false };
  try {
    const res = await fetch(`http://127.0.0.1:${rec.port}/health`, {
      signal: AbortSignal.timeout(PROBE_TIMEOUT_MS),
    });
    if (!res.ok) return { running: false };
    const body = (await res.json().catch(() => null)) as {
      ok?: boolean;
      pid?: number;
      workspace?: string;
    } | null;
    if (body?.ok !== true || body.workspace !== routing.name || body.pid !== rec.pid) {
      return { running: false };
    }
    return { running: true, pid: rec.pid, port: rec.port };
  } catch {
    return { running: false };
  }
}

/** Connect to the workspace daemon (`?p=<projectId>`) and run `fn` (active path). */
export async function withWorkspaceDaemon<T>(
  opts: DaemonClientOptions,
  routing: WorkspaceRouting,
  fn: (caller: DaemonToolCaller) => Promise<T>,
): Promise<T> {
  // Spec §11: a write/read against a workspace whose daemon is DOWN must fail
  // with clear guidance, NOT silently auto-start a fresh daemon (which would
  // look identical to "up" but surprise the user). Probe-only — no ensure.
  const probe = await probeWorkspaceDaemon(routing);
  if (!probe.running || probe.port === undefined) {
    fail(
      EXIT.DAEMON_DOWN,
      `workspace ${JSON.stringify(routing.name)} daemon is not running — start it with \`noir daemon start --workspace ${routing.name}\` (or run \`noir workspace status\`).`,
      opts,
    );
  }
  const url = `http://127.0.0.1:${probe.port}/mcp?p=${routing.projectId}`;
  let client: Client | undefined;
  try {
    client = newClient();
    const connected: Client = client;
    // The workspace daemon's token scope key is the workspace NAME — its own
    // secret, resolved from disk at connect time like every other token. In
    // particular the CALLER's project token is never handed to a workspace
    // server: the two scope keys are different identities, so a repo can only
    // ever present the credential of the daemon it is actually addressing.
    // `connectRaw` (not `connectClient`) so a 401 rejection reaches
    // `failWorkspaceConnect` with its cause intact, instead of being flattened
    // into the generic "daemon not reachable" hint.
    await connectRaw(connected, url, routing.name).catch((err: unknown) =>
      failWorkspaceConnect(opts, routing, err),
    );
    return await fn(buildCaller(connected, opts));
  } finally {
    if (client) {
      await client.close().catch(() => {
        /* a close error must not mask the real failure */
      });
    }
  }
}

/** Open the workspace store read-only and run `fn` over a memory engine (read fallback). */
export async function withWorkspaceMemoryRead<T>(
  opts: DaemonClientOptions,
  routing: WorkspaceRouting,
  project: ProjectInfo,
  fn: (memory: MemoryEngine) => Promise<T>,
): Promise<T> {
  let store: Store;
  try {
    store = await openStore({
      projectId: `ws-${routing.name}`,
      root: project.root,
      dbPath: workspaceStoreDbPath(routing.name),
      readonly: true,
    });
  } catch (err) {
    // Reached only when the workspace daemon is already down (this is its read
    // fallback). The dominant cause is a store that was never created, so give
    // the same actionable guidance + DAEMON_DOWN exit code the active path uses
    // rather than a bare store-open error — the caller's next step is the same
    // either way: start the daemon.
    fail(
      EXIT.DAEMON_DOWN,
      `workspace ${JSON.stringify(routing.name)} store is unavailable (${err instanceof Error ? err.message : String(err)}) — start its daemon with \`noir daemon start --workspace ${routing.name}\` (or run \`noir workspace status\`).`,
      opts,
    );
  }
  const embedderCfg = resolveEmbedderConfig(project.config.context);
  const embed = createEmbedFn(embedderCfg).embed;
  const memory = createMemoryEngine({
    store,
    root: project.root,
    projectId: `ws-${routing.name}`,
    embed,
    storeDegraded: true,
    softForget: true,
  });
  try {
    return await fn(memory);
  } finally {
    await store.close().catch(() => {
      /* a close error must not mask the command's outcome */
    });
  }
}
