import { describe, expect, it } from 'vitest';
import { AGENTS_MD_FILENAME, emitAgentsMd } from '../src/agents-md.js';
import { agentsMdAdapter } from '../src/agents-md-adapter.js';
import { claudeAdapter } from '../src/claude.js';
import { cursorAdapter } from '../src/cursor.js';
import { geminiAdapter } from '../src/gemini.js';
import { resolveAdapter, SUPPORTED_HOSTS } from '../src/index.js';
import { opencodeAdapter } from '../src/opencode.js';
import type { HostId } from '../src/types.js';

describe('SUPPORTED_HOSTS', () => {
  it('lists all five S10 hosts with claude first (the default)', () => {
    expect(SUPPORTED_HOSTS).toEqual(['claude', 'agents-md', 'gemini', 'cursor', 'opencode']);
  });

  it('is readonly (frozen-shape) so consumers cannot mutate the registry list', () => {
    // Object.isFrozen is the strongest runtime signal we can assert; even if
    // not frozen, the `readonly` type prevents compile-time mutation.
    expect(Object.isFrozen(SUPPORTED_HOSTS)).toBe(true);
  });
});

describe('resolveAdapter — S10-Adapters registry (all 5 hosts wired)', () => {
  // The S10-Foundation "coming in S10" throw assertions are now FLIPPED — every
  // host resolves to a real adapter. The exhaustiveness `default: never` guard
  // in resolveAdapter stays (defensive — untyped JS callers still get a clear
  // error if they pass a non-HostId string).

  it('returns the claude adapter for the claude host (the regression anchor)', () => {
    const adapter = resolveAdapter('claude');
    expect(adapter).toBe(claudeAdapter);
    expect(adapter.id).toBe('claude');
  });

  it('returns the agents-md adapter (the universal baseline)', () => {
    const adapter = resolveAdapter('agents-md');
    expect(adapter).toBe(agentsMdAdapter);
    expect(adapter.id).toBe('agents-md');
  });

  it('returns the gemini adapter', () => {
    const adapter = resolveAdapter('gemini');
    expect(adapter).toBe(geminiAdapter);
    expect(adapter.id).toBe('gemini');
  });

  it('returns the cursor adapter', () => {
    const adapter = resolveAdapter('cursor');
    expect(adapter).toBe(cursorAdapter);
    expect(adapter.id).toBe('cursor');
  });

  it('returns the opencode adapter', () => {
    const adapter = resolveAdapter('opencode');
    expect(adapter).toBe(opencodeAdapter);
    expect(adapter.id).toBe('opencode');
  });

  it.each(['claude', 'agents-md', 'gemini', 'cursor', 'opencode'] satisfies HostId[])(
    'every supported host resolves (no host throws) — %s',
    (host) => {
      expect(() => resolveAdapter(host)).not.toThrow();
      expect(resolveAdapter(host).id).toBe(host);
    },
  );

  it('all five hosts are wired (the registry is complete — no host left as a stub)', () => {
    // The S10-Foundation contract shipped 5 hosts in SUPPORTED_HOSTS but only
    // claude resolved. S10-Adapters completes the registry: every supported
    // host now returns a real adapter (the `default: never` guard remains as
    // defensive coverage for future HostId additions).
    for (const host of SUPPORTED_HOSTS) {
      const adapter = resolveAdapter(host);
      expect(adapter.id).toBe(host);
    }
  });
});

describe('emitAgentsMd — the universal shared helper', () => {
  it('exposes AGENTS_MD_FILENAME as the constant "AGENTS.md"', () => {
    expect(AGENTS_MD_FILENAME).toBe('AGENTS.md');
  });

  it('returns content that @-imports the canonical .noir sources', () => {
    const md = emitAgentsMd({ root: '/tmp/demo' });
    expect(md).toContain('@.noir/NOIR.md');
    expect(md).toContain('@.noir/rules/RULES.md');
  });

  it('header uses the project name derived from the root basename', () => {
    const md = emitAgentsMd({ root: '/tmp/my-cool-project' });
    expect(md.startsWith('# my-cool-project — Noir-managed agent context\n')).toBe(true);
  });

  it('header strips trailing slashes from the root before deriving the name', () => {
    const md = emitAgentsMd({ root: '/tmp/demo/' });
    expect(md).toMatch(/^# demo — Noir-managed agent context\n/);
  });

  it('falls back to the literal "project" when the basename is empty', () => {
    const md = emitAgentsMd({ root: '' });
    expect(md).toMatch(/^# project — Noir-managed agent context\n/);
  });

  it('carries the "Generated by noir" + "edit in .noir/" guidance line', () => {
    const md = emitAgentsMd({ root: '/tmp/demo' });
    expect(md).toContain('Generated by `noir`');
    expect(md).toContain('Canonical source lives in `.noir/`');
    expect(md).toContain('`noir sync`');
  });

  it('I2: carries an inline fallback summary BEFORE the @-imports (for readers that do not resolve @)', () => {
    // The fallback sits BEFORE the @-imports so a viewer that does NOT resolve
    // `@`-imports still gets a one-glance pointer to .noir/. Order matters:
    // fallback first, then the canonical imports.
    const md = emitAgentsMd({ root: '/tmp/demo' });
    const fallbackIdx = md.indexOf('Noir manages this project');
    const noirImportIdx = md.indexOf('@.noir/NOIR.md');
    const rulesImportIdx = md.indexOf('@.noir/rules/RULES.md');
    expect(fallbackIdx).toBeGreaterThanOrEqual(0);
    expect(noirImportIdx).toBeGreaterThan(fallbackIdx);
    expect(rulesImportIdx).toBeGreaterThan(fallbackIdx);
    // The fallback names both canonical sources + the re-emit command.
    expect(md).toContain('`.noir/NOIR.md`');
    expect(md).toContain('`.noir/rules/RULES.md`');
    expect(md).toMatch(/re-emit host files/);
  });

  it('produces a stable shape (byte-identical across hosts — the SSOT invariant)', () => {
    // Two different roots produce headings that differ ONLY in the project name
    // — the body (guidance + @-imports) is identical. This is the S10
    // "single-source-of-truth" guarantee: every adapter composes THIS helper so
    // AGENTS.md stays uniform across hosts (modulo the project label).
    const a = emitAgentsMd({ root: '/tmp/aaa' });
    const b = emitAgentsMd({ root: '/tmp/bbb' });
    const aBody = a.split('\n\n').slice(1).join('\n\n');
    const bBody = b.split('\n\n').slice(1).join('\n\n');
    expect(aBody).toBe(bBody);
  });
});
