import { describe, expect, it } from 'vitest';
import { AGENTS_MD_FILENAME, emitAgentsMd } from '../src/agents-md.js';
import { claudeAdapter } from '../src/claude.js';
import { resolveAdapter, SUPPORTED_HOSTS } from '../src/index.js';
import type { HostId } from '../src/types.js';

describe('SUPPORTED_HOSTS', () => {
  it('lists all five S10 hosts with claude first (the default)', () => {
    expect(SUPPORTED_HOSTS).toEqual(['claude', 'agents-md', 'gemini', 'cursor', 'opencode']);
  });

  it('is readonly (frozen-shape) so consumers cannot mutate the registry list', () => {
    // Object.isFrozen is the strongest runtime signal we can assert; even if
    // not frozen, the `readonly` type prevents compile-time mutation.
    expect(Object.isFrozen(SUPPORTED_HOSTS)).toBe(true);
  });
});

describe('resolveAdapter — S10-Foundation registry', () => {
  it('returns the claude adapter for the claude host (the regression anchor)', () => {
    const adapter = resolveAdapter('claude');
    expect(adapter).toBe(claudeAdapter);
    expect(adapter.id).toBe('claude');
  });

  it.each(['agents-md', 'gemini', 'cursor', 'opencode'] satisfies HostId[])(
    'throws a clear "coming in S10" error for %s (wired in the next slice)',
    (host) => {
      expect(() => resolveAdapter(host)).toThrow(/Unsupported host: .* \(coming in S10\)/);
    },
  );

  it('the four non-claude hosts are part of HostId but not yet resolvable', () => {
    // Sanity: the foundation ships the FULL shape (5 hosts in SUPPORTED_HOSTS)
    // but only claude resolves. This is the documented S10-Foundation contract.
    const nonClaude = SUPPORTED_HOSTS.filter((h) => h !== 'claude');
    expect(nonClaude).toEqual(['agents-md', 'gemini', 'cursor', 'opencode']);
    for (const host of nonClaude) {
      expect(() => resolveAdapter(host)).toThrow();
    }
  });
});

describe('emitAgentsMd — the universal shared helper', () => {
  it('exposes AGENTS_MD_FILENAME as the constant "AGENTS.md"', () => {
    expect(AGENTS_MD_FILENAME).toBe('AGENTS.md');
  });

  it('returns content that @-imports the canonical .noir sources', () => {
    const md = emitAgentsMd({ root: '/tmp/demo' });
    expect(md).toContain('@.noir/NOIR.md');
    expect(md).toContain('@.noir/rules/RULES.md');
  });

  it('header uses the project name derived from the root basename', () => {
    const md = emitAgentsMd({ root: '/tmp/my-cool-project' });
    expect(md.startsWith('# my-cool-project — Noir-managed agent context\n')).toBe(true);
  });

  it('header strips trailing slashes from the root before deriving the name', () => {
    const md = emitAgentsMd({ root: '/tmp/demo/' });
    expect(md).toMatch(/^# demo — Noir-managed agent context\n/);
  });

  it('falls back to the literal "project" when the basename is empty', () => {
    const md = emitAgentsMd({ root: '' });
    expect(md).toMatch(/^# project — Noir-managed agent context\n/);
  });

  it('carries the "Generated by noir" + "edit in .noir/" guidance line', () => {
    const md = emitAgentsMd({ root: '/tmp/demo' });
    expect(md).toContain('Generated by `noir`');
    expect(md).toContain('Canonical source lives in `.noir/`');
    expect(md).toContain('`noir sync`');
  });

  it('produces a stable shape (byte-identical across hosts — the SSOT invariant)', () => {
    // Two different roots produce headings that differ ONLY in the project name
    // — the body (guidance + @-imports) is identical. This is the S10
    // "single-source-of-truth" guarantee: every adapter composes THIS helper so
    // AGENTS.md stays uniform across hosts (modulo the project label).
    const a = emitAgentsMd({ root: '/tmp/aaa' });
    const b = emitAgentsMd({ root: '/tmp/bbb' });
    const aBody = a.split('\n\n').slice(1).join('\n\n');
    const bBody = b.split('\n\n').slice(1).join('\n\n');
    expect(aBody).toBe(bBody);
  });
});
