import { basename } from 'node:path';
import type { EmitContext } from './types.js';

/** The canonical filename for the universal AGENTS.md emitter. Every host
 *  writes the SAME content (single source of truth) — adapters may place it at
 *  different paths via `HostAdapter#agentsMdPath`, but the filename is constant. */
export const AGENTS_MD_FILENAME = 'AGENTS.md';

/**
 * The universal AGENTS.md emitter — a SHARED HELPER composed by every adapter
 * (NOT a HostAdapter itself). AGENTS.md is now the cross-tool standard (32+
 * platforms read it natively — Claude Code, OpenAI Codex, Cursor, Gemini CLI,
 * JetBrains Junie, …), so the SAME file content works for every host: it
 * `@`-imports the canonical `.noir/` sources. Per-host specialization lives in
 * each adapter's OWN native files (CLAUDE.md, GEMINI.md, .cursor/rules/*.mdc,
 * opencode.json); AGENTS.md is the always-emitted universal baseline.
 *
 * Content (byte-identical across hosts):
 *
 *   # <projectName> — Noir-managed agent context
 *
 *   > Generated by `noir`. Canonical source lives in `.noir/`. Edit there; re-run `noir sync`.
 *
 *   > Noir manages this project's context under `.noir/`. Edit `.noir/NOIR.md`
 *   > (project brief) + `.noir/rules/RULES.md` (working contract); re-run
 *   > `noir sync` to re-emit host files.
 *
 *   @.noir/NOIR.md
 *   @.noir/rules/RULES.md
 *
 * The inline 3-line fallback sits BEFORE the `@`-imports so AGENTS.md
 * readers that do NOT resolve `@`-imports (e.g. plain markdown viewers, some
 * GA dashboards) still get a one-glance summary of where to edit. The
 * `@`-imports remain canonical for the hosts that DO resolve them (Cursor,
 * Codex, Junie, …).
 *
 * A project that switched the working rules off (`ctx.rulesEnabled: false`)
 * has no `.noir/rules/RULES.md` — the scaffold withholds the seed — so both
 * the import line AND the sentence that names it are dropped. An `@`-import
 * of a file that is not there is a dangling reference the host resolves to
 * nothing, and prose pointing the reader at it is worse. The brief import
 * stays either way: the switch gates the rules, not the context.
 *
 * `<projectName>` is derived from `ctx.root`'s basename — a best-effort label
 * for human readability. If the basename is empty/undeterminable, falls back to
 * the literal `project` so the heading is never malformed.
 */
export function emitAgentsMd(ctx: EmitContext): string {
  const projectName = deriveProjectName(ctx.root);
  const rules = ctx.rulesEnabled !== false;
  const managedProse = rules
    ? `> Noir manages this project's context under \`.noir/\`. Edit \`.noir/NOIR.md\` ` +
      `(project brief) + \`.noir/rules/RULES.md\` (working contract); re-run \`noir sync\` ` +
      `to re-emit host files.\n\n`
    : `> Noir manages this project's context under \`.noir/\`. Edit \`.noir/NOIR.md\` ` +
      `(project brief); re-run \`noir sync\` to re-emit host files.\n\n`;
  const imports = rules ? `@.noir/NOIR.md\n@.noir/rules/RULES.md\n` : `@.noir/NOIR.md\n`;
  return (
    `# ${projectName} — Noir-managed agent context\n\n` +
    `> Generated by \`noir\`. Canonical source lives in \`.noir/\`. Edit there; re-run \`noir sync\`.\n\n` +
    managedProse +
    imports
  );
}

/** Derive a human-readable project label from the root path's basename.
 *  Trims trailing slashes (POSIX) so `/p/demo/` → `demo`; falls back to the
 *  literal `project` when the basename is empty (e.g. root was `/` or `''`). */
function deriveProjectName(root: string): string {
  // `basename` already handles trailing slashes on POSIX; guard the empty case.
  const name = basename(root.replace(/\/+$/, '')) || basename(root);
  return name && name.length > 0 ? name : 'project';
}
