import { basename } from 'node:path';
import type { EmitContext } from './types.js';

/** The canonical filename for the universal AGENTS.md emitter. Every host
 *  writes the SAME content (single source of truth) — adapters may place it at
 *  different paths via `HostAdapter#agentsMdPath`, but the filename is constant. */
export const AGENTS_MD_FILENAME = 'AGENTS.md';

/**
 * The universal AGENTS.md emitter — a SHARED HELPER composed by every adapter
 * (NOT a HostAdapter itself). AGENTS.md is now the cross-tool standard (32+
 * platforms read it natively — Claude Code, OpenAI Codex, Cursor, Gemini CLI,
 * JetBrains Junie, …), so the SAME file content works for every host: it
 * `@`-imports the canonical `.noir/` sources. Per-host specialization lives in
 * each adapter's OWN native files (CLAUDE.md, GEMINI.md, .cursor/rules/*.mdc,
 * opencode.json); AGENTS.md is the always-emitted universal baseline.
 *
 * Content (byte-identical across hosts):
 *
 *   # <projectName> — Noir-managed agent context
 *
 *   > Generated by `noir`. Canonical source lives in `.noir/`. Edit there; re-run `noir sync`.
 *
 *   @.noir/NOIR.md
 *   @.noir/rules/RULES.md
 *
 * `<projectName>` is derived from `ctx.root`'s basename — a best-effort label
 * for human readability. If the basename is empty/undeterminable, falls back to
 * the literal `project` so the heading is never malformed.
 */
export function emitAgentsMd(ctx: EmitContext): string {
  const projectName = deriveProjectName(ctx.root);
  return (
    `# ${projectName} — Noir-managed agent context\n\n` +
    `> Generated by \`noir\`. Canonical source lives in \`.noir/\`. Edit there; re-run \`noir sync\`.\n\n` +
    `@.noir/NOIR.md\n` +
    `@.noir/rules/RULES.md\n`
  );
}

/** Derive a human-readable project label from the root path's basename.
 *  Trims trailing slashes (POSIX) so `/p/demo/` → `demo`; falls back to the
 *  literal `project` when the basename is empty (e.g. root was `/` or `''`). */
function deriveProjectName(root: string): string {
  // `basename` already handles trailing slashes on POSIX; guard the empty case.
  const name = basename(root.replace(/\/+$/, '')) || basename(root);
  return name && name.length > 0 ? name : 'project';
}
